### ISSUE TITLE
gramex init UnicodeErrorr

### ISSUE THREAD

**Issue by Xnsam** [gramener/gramex#142]
Hi,

I am trying out a non-commercial version of gramex. 
I installed it all fine until
When i try to do gramex init, i get this error...
python==3.7
anaconda == 5.
gramex==1.53
tornado==5.1.1

`[user@localhost gramex_project_1]$ gramex init
DEBUG   29-Mar 13:37:24 config PORT Loading config: /home/user/anaconda3/lib/python3.7/site-packages/gramex/apps.yaml
DEBUG   29-Mar 13:37:24 config PORT Loading config: /home/user/.config/gramexdata/apps/apps.yaml
INFO    29-Mar 13:37:24 install PORT Initializing Gramex project at /home/user/gramex_project_1
Traceback (most recent call last):
  File "/home/user/anaconda3/bin/gramex", line 11, in <module>
    sys.exit(commandline())
  File "/home/user/anaconda3/lib/python3.7/site-packages/gramex/__init__.py", line 177, in commandline
    callback(**kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/gramex/install.py", line 649, in init
    _copy(source, target, template_data=data)
  File "/home/user/anaconda3/lib/python3.7/site-packages/gramex/install.py", line 616, in _copy
    result = Template(result).generate(**template_data)
  File "/home/user/anaconda3/lib/python3.7/site-packages/tornado/template.py", line 302, in __init__
    reader = _TemplateReader(name, escape.native_str(template_string),
  File "/home/user/anaconda3/lib/python3.7/site-packages/tornado/escape.py", line 217, in to_unicode
    return value.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 8: invalid continuation byte
`

I tried with python2.7 and anaconda2 5.x version as per the requirement, but still this error won't go.

Any suggestions?

**Comment by sanand0** [comment]
@Xnsam could we debug this on a screen-sharing session? Could you please email me at cto@gramener.com with a time that works for you, please?

**Comment by sanand0** [comment]
@CalmDownKarm mentions: "I noticed _copy() in install.py doesn't explicitly set a unicode encoding when it copies the init templates over, Since io.open() will use the system locale's encoding, which could be something other than utf-8.
![gramex error](https://user-images.githubusercontent.com/63734/57274791-f9940980-70b9-11e9-8b23-e5f55c2e6f2c.PNG)
"

**Comment by CalmDownKarm** [comment]
@Xnsam do you have git installed?

@sanand0  I spoke to Pranav who had the same problem, he fixed it by changing the default encoding in tornado's escape.py to iso-8859-1, which fixed the error temporarily. Subsequently installing git and git  bash set his default locale encoding to utf-8 which fixed it between installs. Since we're not using shutil in _copy(), but read and write it using io.open, I strongly suspect that setting an encoding will fix the issue.

**Comment by naiktanmai** [comment]
I installed on python3.7.3 and am facing this issue. Any help would be much appreciated.
