### ISSUE TITLE
Gramex v1.63 upgrade error: LineProfiler does not compile / install with Python 3.7

### ISSUE THREAD

**Issue by nikhilkabbin** [gramener/gramex#283]
Works with Gramex v.162

**Comment by sanand0** [comment]
@jaidevd @nikhilkabbin This happens when the user directly runs `pip install --upgrade gramex` without having run a conda install before.

Today, there is only one package that cannot be installed via pip on Windows -- line_profiler. It's already an optional dependency. Gramex will run without it -- and warn users if they try to use line profiling.

So I've changed `setup.py` to ONLY try to install packages that *can* be installed via pip.

Now, `pip install gramex` should work across platforms. Could you **please test**?
