### ISSUE TITLE
Dynamic queries for caching FormHandler

### ISSUE THREAD

**Issue by mniyas** [gramener/gramex#341]
**Is your feature request related to a problem? Please describe.**
I would like to use a function to dynamically create the query for caching in FormHandler. Like below.
     
     config_name:
          pattern: /$YAMLURL/pattern
          handler: FormHandler
          kwargs:
              url: $CONN
              table: utils.cache_query(handler)
              queryfunction: utils.actual_query(handler)

**Describe the solution you'd like**
I want `table` parameter to accept a python function or add a new parameter like `queryfunction` to accept a state function.

**Comment by sanand0** [comment]
@mniyas I'll call you to discuss possible options.

**Comment by sanand0** [comment]
@mniyas Could we plan this as follows:

- In `FormHandler`, add `state` under `function_vars`. This allows a YAML config like `state: utils.state(args, handler.request.path)` as an expression that returns the state
- In `data.filter`, instead of `state = None`, use `state = kwargs.pop('state', None)`. If `state` is still None, then pick it up from table
- In `tests/gramex.yaml`, add a `formhandler/sqlite-state` that sets the `state: utils.state(args, handler)`. 
- In `utils.py`
    - add a `state(*args)` that does a `state_info.append(*args)`
    - add a FunctionHandler at `/formhandler/state` that calls `utils.get_state_info()` which returns `state_info`
- In `test_formhandler.py`, under `TestFormHandler.test_sqlite`, test the following:
    - `/formhandler/state` returns `[]` -- i.e. `state()` has not been called so far
    - `self.check_filter('/formhandler/sqlite-state?x=1', na_position='last')` passes
    - `/formhandler/state` returns a single list with `[{"x": 1}, "/formhandler/sqlite-state"]`, indicating that `state()` has been called exactly once with the right arguments
