### ISSUE TITLE
Add aliases to Gramex Components/Handlers/Libraries

### ISSUE THREAD

**Issue by bhatsandeep** [gramener/gramex#350]
**Is your feature request related to a problem? Please describe.**
Users do not intuitively understand the underlying functionality of Gramex components

**Describe the solution you'd like**
Provide simpler and intuitive alias for each component

**Describe alternatives you've considered**
-
**Additional context**
Suggested Aliases are in attached file!
[Renaming Gramex Components.xlsx](https://github.com/gramener/gramex/files/5707182/Renaming.Gramex.Components.xlsx)

**Comment by jaidevd** [comment]
Thanks, @bhatsandeep. After you have finalized the names, @sanand0 will come back with an estimate of when this will be done. Anand, can we target this for the next release?

**Comment by bhatsandeep** [comment]
@jaidevd finalized aliases are already attached to this issue

**Comment by sanand0** [comment]
Yes, we'll target it for 1.67 on 1 Jan 2021.

**Comment by sanand0** [comment]
I've renamed the services:

```
Command = ProcessHandler
Data = FormHandler
Facebook = FacebookGraphHandler
File = DirectoryHandler = FileHandler
Filter = FilterHandler
Function = FunctionHandler
Proxy = ProxyHandler
Screenshot = CaptureHandler
Slide = PPTXHandler
Storage = DriveHandler
Twitter = TwitterRESTHandler
Websocket = WebSocketHandler
```

Plus, `service:` is an alias to `handler:` with higher priority.

I have not changed the following:

- AuthHandlers (e.g. GoogleAuth to auth.Google) -- since the current structure seems fine
- ModelHandler to ML -- since we'll create a new MLHander
- JSONHandler to GraphDB -- since this is undecided
- Other services (e.g. SendEmail, SmartAlerts, etc -- the renaming structure wasn't clear)
- g1 -- since the plan is undecided

@bhatsandeep -- your thoughts?
