### ISSUE TITLE
Formhandler - Exception or Errors raised must send clear messages in json response

### ISSUE THREAD

**Issue by tejesh95** [gramener/gramex#77]
Example:

Currently, for 400 status errors send error as "error" and message as "" 

Expected: error as "Bad Request Error" and message as "Primary key XX is mandatory to edit/add a row"

raised by @bkamapantula

**Comment by sanand0** [comment]
@bkamapantula @tejesh95 -- FormHandler sends output in a variety of formats: JSON, CSV, HTML, etc. When an error is rendered, we always send the output as HTML. I would prefer this over JSON since it's human readable.

Currently, we use the HTTP status header to send information. I'll modify it so that $.formhandler says this:

![image](https://user-images.githubusercontent.com/63734/53302284-db708880-3882-11e9-8816-98a25f260c1c.png)

... instead of this:

![image](https://user-images.githubusercontent.com/63734/53302285-df9ca600-3882-11e9-9490-c93997d5eef9.png)

**Comment by pratapvardhan** [comment]
Related #189 -- example to customize error responses
