### ISSUE TITLE
FormHandler should support REST API for multiple sorts

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#92]
FormHandler should support sorting as `_sort:<col>=asc` and `_sort:<col>=desc`, or some such mechanism that allows different sort keys for different columns. This makes it easier to update sorting directly using URL filters.

For example, if there are 3 columns, X, Y, Z, we can have 6 links for sort ascending / descending on each column. These links can all apply independently. Ascending / Descending will overwrite each other, but not interfere with the sorts of other columns.

This can be implemented in a backward-compatible way as well, i.e. we respect `_sort=` as well as `_sort:<col>=`.

**Comment by pratapvardhan** [comment]
@sanand0 -- it's not clear to me why would we need `_sort=<col>=<order>` over `_sort=</-><col>` . Could you document test/usecases where former is need?

**Comment by sanand0** [comment]
@tejesh95 Could you please comment on this, based on our discussion?

**Comment by tejesh95** [comment]
With `_sort:<col>=<order>` multisorting of columns will become as easy as single sort with `_sort=</-><col>`

In other words, with current spec if requirement is to sort by different `<other_col>` , solution is **add** and url becomes `_sort=<col>&_sort=<other_col>`
But if requirement is to sort by same col but descending, solution is to **update** same key. url becomes `_sort=-<col>`. So, state of current URL decides the operator action of `_sort` (whether *update* or *add*)

The problem is having the same key (`_sort`) irrespective of column to be sorted. Bringing `<col>` in to key, would need only **update** operation irrespective of current url.

**Comment by pratapvardhan** [comment]
For g1 we have solved it with [g1@b57ab9dd](https://code.gramener.com/cto/g1/commit/b57ab9ddbb0fcd65c65089a1ae3f314f5b6af634).

We can defer this for now.
